/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 particle_effect.glb --transform 
Files: particle_effect.glb [8.8MB] > /home/kevin-s/javascript/teamk/public/particle_effect-transformed.glb [204.51KB] (98%)
Author: bigspoon (https://sketchfab.com/bigspoon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/particle-effect-757f8e075377427e894353c8c1d071df
Title: Particle Effect
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'


export function Particle_effect(props) {
  const { nodes, materials } = useGLTF('/particle_effect-transformed.glb')
  const springOptions = { bounce: 0.1 };

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Icosphere__0.geometry} material={materials.Icosphere__0} position={[-0.003, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={1.294} />
      <mesh geometry={nodes['Icosphere|Icosphere001|Dupli|_Material001_0'].geometry} material={materials['Material.001']} position={[-0.054, 1.008, -0.689]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.038} />
    </group>
  )
}

useGLTF.preload('/particle_effect-transformed.glb')
